language: node_js
node_js:
  - "10.15.3"


jobs:
  include:
  - stage: test
    os: osx
    before_script: npm run-script build
    install: npm i -g recursive-install && npm-recursive-install

    addons:
      chrome: stable

    after_success:
      - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
      - chmod +x send.sh
      - ./send.sh success $WEBHOOK_URL
    after_failure:
      - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
      - chmod +x send.sh
      - ./send.sh failure $WEBHOOK_URL

  - stage: deploy
    if: type = push AND repo = orange-alliance/the-orange-alliance AND branch = master
    script: curl $DEPLOY_SCRIPT | bash
